openapi: 3.0.0
info:
  title: 03-jobs-API
  version: 1.0.0
servers:
  - url: https://jobs-api-ts70.onrender.com/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: auth
  - name: Jobs
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: jess
                email: john@1gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: john@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: sofip
                position: back front-end dev
                status: en attente
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmZhNTVhYmVkODFhMzk5NDYxNmZlZGIiLCJpYXQiOjE3Mjc2ODQzMjgsImV4cCI6MTcyNzc3MDcyOH0.W1QXV33O1ay7BH299JyScr9Ooq-8G1Efo28w2d6cvVc
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Jobs
      summary: Update Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: sofip
                position: back front-end dev
                status: en attente
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: Delete Job
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
